
# Database credentials
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docsfeedback
    username: postgres
    password: test

# Hibernate logging
logging.level:
  org:
    springframework:
      web: DEBUG
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE